// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompanyCreatedPackage.proto

package com.mining.platform.company;

public final class CompanyCreatedPackageOuterClass {
  private CompanyCreatedPackageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompanyCreatedPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mining.platform.company.CompanyCreatedPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes companyId = 1;</code>
     */
    com.google.protobuf.ByteString getCompanyId();
  }
  /**
   * Protobuf type {@code com.mining.platform.company.CompanyCreatedPackage}
   */
  public  static final class CompanyCreatedPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mining.platform.company.CompanyCreatedPackage)
      CompanyCreatedPackageOrBuilder {
    // Use CompanyCreatedPackage.newBuilder() to construct.
    private CompanyCreatedPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompanyCreatedPackage() {
      companyId_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CompanyCreatedPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              companyId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mining.platform.company.CompanyCreatedPackageOuterClass.internal_static_com_mining_platform_company_CompanyCreatedPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mining.platform.company.CompanyCreatedPackageOuterClass.internal_static_com_mining_platform_company_CompanyCreatedPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage.class, com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage.Builder.class);
    }

    public static final int COMPANYID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString companyId_;
    /**
     * <code>optional bytes companyId = 1;</code>
     */
    public com.google.protobuf.ByteString getCompanyId() {
      return companyId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!companyId_.isEmpty()) {
        output.writeBytes(1, companyId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!companyId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, companyId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage)) {
        return super.equals(obj);
      }
      com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage other = (com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage) obj;

      boolean result = true;
      result = result && getCompanyId()
          .equals(other.getCompanyId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + COMPANYID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mining.platform.company.CompanyCreatedPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mining.platform.company.CompanyCreatedPackage)
        com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mining.platform.company.CompanyCreatedPackageOuterClass.internal_static_com_mining_platform_company_CompanyCreatedPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mining.platform.company.CompanyCreatedPackageOuterClass.internal_static_com_mining_platform_company_CompanyCreatedPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage.class, com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage.Builder.class);
      }

      // Construct using com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        companyId_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mining.platform.company.CompanyCreatedPackageOuterClass.internal_static_com_mining_platform_company_CompanyCreatedPackage_descriptor;
      }

      public com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage getDefaultInstanceForType() {
        return com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage.getDefaultInstance();
      }

      public com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage build() {
        com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage buildPartial() {
        com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage result = new com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage(this);
        result.companyId_ = companyId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage) {
          return mergeFrom((com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage other) {
        if (other == com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage.getDefaultInstance()) return this;
        if (other.getCompanyId() != com.google.protobuf.ByteString.EMPTY) {
          setCompanyId(other.getCompanyId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString companyId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes companyId = 1;</code>
       */
      public com.google.protobuf.ByteString getCompanyId() {
        return companyId_;
      }
      /**
       * <code>optional bytes companyId = 1;</code>
       */
      public Builder setCompanyId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes companyId = 1;</code>
       */
      public Builder clearCompanyId() {
        
        companyId_ = getDefaultInstance().getCompanyId();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.mining.platform.company.CompanyCreatedPackage)
    }

    // @@protoc_insertion_point(class_scope:com.mining.platform.company.CompanyCreatedPackage)
    private static final com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage();
    }

    public static com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompanyCreatedPackage>
        PARSER = new com.google.protobuf.AbstractParser<CompanyCreatedPackage>() {
      public CompanyCreatedPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CompanyCreatedPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CompanyCreatedPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompanyCreatedPackage> getParserForType() {
      return PARSER;
    }

    public com.mining.platform.company.CompanyCreatedPackageOuterClass.CompanyCreatedPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mining_platform_company_CompanyCreatedPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mining_platform_company_CompanyCreatedPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CompanyCreatedPackage.proto\022\033com.minin" +
      "g.platform.company\"*\n\025CompanyCreatedPack" +
      "age\022\021\n\tcompanyId\030\001 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mining_platform_company_CompanyCreatedPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mining_platform_company_CompanyCreatedPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mining_platform_company_CompanyCreatedPackage_descriptor,
        new java.lang.String[] { "CompanyId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
