// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChecklistPackage.proto

package com.mining.platform.checklist;

public final class ChecklistPackageOuterClass {
  private ChecklistPackageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChecklistItemPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mining.platform.checklist.ChecklistItemPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.mining.platform.checklist.ChecklistItemPackage}
   */
  public  static final class ChecklistItemPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mining.platform.checklist.ChecklistItemPackage)
      ChecklistItemPackageOrBuilder {
    // Use ChecklistItemPackage.newBuilder() to construct.
    private ChecklistItemPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChecklistItemPackage() {
      id_ = "";
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChecklistItemPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistItemPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistItemPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.class, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage)) {
        return super.equals(obj);
      }
      com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage other = (com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getName()
          .equals(other.getName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mining.platform.checklist.ChecklistItemPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mining.platform.checklist.ChecklistItemPackage)
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistItemPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistItemPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.class, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder.class);
      }

      // Construct using com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistItemPackage_descriptor;
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage getDefaultInstanceForType() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.getDefaultInstance();
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage build() {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage buildPartial() {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage result = new com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage(this);
        result.id_ = id_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage) {
          return mergeFrom((com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage other) {
        if (other == com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.mining.platform.checklist.ChecklistItemPackage)
    }

    // @@protoc_insertion_point(class_scope:com.mining.platform.checklist.ChecklistItemPackage)
    private static final com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage();
    }

    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChecklistItemPackage>
        PARSER = new com.google.protobuf.AbstractParser<ChecklistItemPackage>() {
      public ChecklistItemPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChecklistItemPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChecklistItemPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChecklistItemPackage> getParserForType() {
      return PARSER;
    }

    public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChecklistPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mining.platform.checklist.ChecklistPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage> 
        getChecklistItemsList();
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage getChecklistItems(int index);
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    int getChecklistItemsCount();
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    java.util.List<? extends com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder> 
        getChecklistItemsOrBuilderList();
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder getChecklistItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.mining.platform.checklist.ChecklistPackage}
   */
  public  static final class ChecklistPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mining.platform.checklist.ChecklistPackage)
      ChecklistPackageOrBuilder {
    // Use ChecklistPackage.newBuilder() to construct.
    private ChecklistPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChecklistPackage() {
      id_ = "";
      name_ = "";
      checklistItems_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChecklistPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                checklistItems_ = new java.util.ArrayList<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage>();
                mutable_bitField0_ |= 0x00000004;
              }
              checklistItems_.add(
                  input.readMessage(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          checklistItems_ = java.util.Collections.unmodifiableList(checklistItems_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.class, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHECKLISTITEMS_FIELD_NUMBER = 3;
    private java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage> checklistItems_;
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    public java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage> getChecklistItemsList() {
      return checklistItems_;
    }
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    public java.util.List<? extends com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder> 
        getChecklistItemsOrBuilderList() {
      return checklistItems_;
    }
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    public int getChecklistItemsCount() {
      return checklistItems_.size();
    }
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage getChecklistItems(int index) {
      return checklistItems_.get(index);
    }
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
     */
    public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder getChecklistItemsOrBuilder(
        int index) {
      return checklistItems_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < checklistItems_.size(); i++) {
        output.writeMessage(3, checklistItems_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < checklistItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, checklistItems_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage)) {
        return super.equals(obj);
      }
      com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage other = (com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getChecklistItemsList()
          .equals(other.getChecklistItemsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getChecklistItemsCount() > 0) {
        hash = (37 * hash) + CHECKLISTITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getChecklistItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mining.platform.checklist.ChecklistPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mining.platform.checklist.ChecklistPackage)
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.class, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder.class);
      }

      // Construct using com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChecklistItemsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        if (checklistItemsBuilder_ == null) {
          checklistItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          checklistItemsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistPackage_descriptor;
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage getDefaultInstanceForType() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.getDefaultInstance();
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage build() {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage buildPartial() {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage result = new com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (checklistItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            checklistItems_ = java.util.Collections.unmodifiableList(checklistItems_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.checklistItems_ = checklistItems_;
        } else {
          result.checklistItems_ = checklistItemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage) {
          return mergeFrom((com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage other) {
        if (other == com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (checklistItemsBuilder_ == null) {
          if (!other.checklistItems_.isEmpty()) {
            if (checklistItems_.isEmpty()) {
              checklistItems_ = other.checklistItems_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureChecklistItemsIsMutable();
              checklistItems_.addAll(other.checklistItems_);
            }
            onChanged();
          }
        } else {
          if (!other.checklistItems_.isEmpty()) {
            if (checklistItemsBuilder_.isEmpty()) {
              checklistItemsBuilder_.dispose();
              checklistItemsBuilder_ = null;
              checklistItems_ = other.checklistItems_;
              bitField0_ = (bitField0_ & ~0x00000004);
              checklistItemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChecklistItemsFieldBuilder() : null;
            } else {
              checklistItemsBuilder_.addAllMessages(other.checklistItems_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage> checklistItems_ =
        java.util.Collections.emptyList();
      private void ensureChecklistItemsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          checklistItems_ = new java.util.ArrayList<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage>(checklistItems_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder> checklistItemsBuilder_;

      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage> getChecklistItemsList() {
        if (checklistItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(checklistItems_);
        } else {
          return checklistItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public int getChecklistItemsCount() {
        if (checklistItemsBuilder_ == null) {
          return checklistItems_.size();
        } else {
          return checklistItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage getChecklistItems(int index) {
        if (checklistItemsBuilder_ == null) {
          return checklistItems_.get(index);
        } else {
          return checklistItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder setChecklistItems(
          int index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage value) {
        if (checklistItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistItemsIsMutable();
          checklistItems_.set(index, value);
          onChanged();
        } else {
          checklistItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder setChecklistItems(
          int index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder builderForValue) {
        if (checklistItemsBuilder_ == null) {
          ensureChecklistItemsIsMutable();
          checklistItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          checklistItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder addChecklistItems(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage value) {
        if (checklistItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistItemsIsMutable();
          checklistItems_.add(value);
          onChanged();
        } else {
          checklistItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder addChecklistItems(
          int index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage value) {
        if (checklistItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistItemsIsMutable();
          checklistItems_.add(index, value);
          onChanged();
        } else {
          checklistItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder addChecklistItems(
          com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder builderForValue) {
        if (checklistItemsBuilder_ == null) {
          ensureChecklistItemsIsMutable();
          checklistItems_.add(builderForValue.build());
          onChanged();
        } else {
          checklistItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder addChecklistItems(
          int index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder builderForValue) {
        if (checklistItemsBuilder_ == null) {
          ensureChecklistItemsIsMutable();
          checklistItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          checklistItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder addAllChecklistItems(
          java.lang.Iterable<? extends com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage> values) {
        if (checklistItemsBuilder_ == null) {
          ensureChecklistItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, checklistItems_);
          onChanged();
        } else {
          checklistItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder clearChecklistItems() {
        if (checklistItemsBuilder_ == null) {
          checklistItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          checklistItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public Builder removeChecklistItems(int index) {
        if (checklistItemsBuilder_ == null) {
          ensureChecklistItemsIsMutable();
          checklistItems_.remove(index);
          onChanged();
        } else {
          checklistItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder getChecklistItemsBuilder(
          int index) {
        return getChecklistItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder getChecklistItemsOrBuilder(
          int index) {
        if (checklistItemsBuilder_ == null) {
          return checklistItems_.get(index);  } else {
          return checklistItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public java.util.List<? extends com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder> 
           getChecklistItemsOrBuilderList() {
        if (checklistItemsBuilder_ != null) {
          return checklistItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(checklistItems_);
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder addChecklistItemsBuilder() {
        return getChecklistItemsFieldBuilder().addBuilder(
            com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder addChecklistItemsBuilder(
          int index) {
        return getChecklistItemsFieldBuilder().addBuilder(
            index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistItemPackage checklistItems = 3;</code>
       */
      public java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder> 
           getChecklistItemsBuilderList() {
        return getChecklistItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder> 
          getChecklistItemsFieldBuilder() {
        if (checklistItemsBuilder_ == null) {
          checklistItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackage.Builder, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistItemPackageOrBuilder>(
                  checklistItems_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          checklistItems_ = null;
        }
        return checklistItemsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.mining.platform.checklist.ChecklistPackage)
    }

    // @@protoc_insertion_point(class_scope:com.mining.platform.checklist.ChecklistPackage)
    private static final com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage();
    }

    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChecklistPackage>
        PARSER = new com.google.protobuf.AbstractParser<ChecklistPackage>() {
      public ChecklistPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChecklistPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChecklistPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChecklistPackage> getParserForType() {
      return PARSER;
    }

    public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChecklistListPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mining.platform.checklist.ChecklistListPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage> 
        getChecklistsList();
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage getChecklists(int index);
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    int getChecklistsCount();
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    java.util.List<? extends com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder> 
        getChecklistsOrBuilderList();
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder getChecklistsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.mining.platform.checklist.ChecklistListPackage}
   */
  public  static final class ChecklistListPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mining.platform.checklist.ChecklistListPackage)
      ChecklistListPackageOrBuilder {
    // Use ChecklistListPackage.newBuilder() to construct.
    private ChecklistListPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChecklistListPackage() {
      checklists_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ChecklistListPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                checklists_ = new java.util.ArrayList<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage>();
                mutable_bitField0_ |= 0x00000001;
              }
              checklists_.add(
                  input.readMessage(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          checklists_ = java.util.Collections.unmodifiableList(checklists_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistListPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistListPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage.class, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage.Builder.class);
    }

    public static final int CHECKLISTS_FIELD_NUMBER = 1;
    private java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage> checklists_;
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    public java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage> getChecklistsList() {
      return checklists_;
    }
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    public java.util.List<? extends com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder> 
        getChecklistsOrBuilderList() {
      return checklists_;
    }
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    public int getChecklistsCount() {
      return checklists_.size();
    }
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage getChecklists(int index) {
      return checklists_.get(index);
    }
    /**
     * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
     */
    public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder getChecklistsOrBuilder(
        int index) {
      return checklists_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < checklists_.size(); i++) {
        output.writeMessage(1, checklists_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < checklists_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, checklists_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage)) {
        return super.equals(obj);
      }
      com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage other = (com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage) obj;

      boolean result = true;
      result = result && getChecklistsList()
          .equals(other.getChecklistsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getChecklistsCount() > 0) {
        hash = (37 * hash) + CHECKLISTS_FIELD_NUMBER;
        hash = (53 * hash) + getChecklistsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mining.platform.checklist.ChecklistListPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mining.platform.checklist.ChecklistListPackage)
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistListPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistListPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage.class, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage.Builder.class);
      }

      // Construct using com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChecklistsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (checklistsBuilder_ == null) {
          checklists_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          checklistsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.internal_static_com_mining_platform_checklist_ChecklistListPackage_descriptor;
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage getDefaultInstanceForType() {
        return com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage.getDefaultInstance();
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage build() {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage buildPartial() {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage result = new com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage(this);
        int from_bitField0_ = bitField0_;
        if (checklistsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            checklists_ = java.util.Collections.unmodifiableList(checklists_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.checklists_ = checklists_;
        } else {
          result.checklists_ = checklistsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage) {
          return mergeFrom((com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage other) {
        if (other == com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage.getDefaultInstance()) return this;
        if (checklistsBuilder_ == null) {
          if (!other.checklists_.isEmpty()) {
            if (checklists_.isEmpty()) {
              checklists_ = other.checklists_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureChecklistsIsMutable();
              checklists_.addAll(other.checklists_);
            }
            onChanged();
          }
        } else {
          if (!other.checklists_.isEmpty()) {
            if (checklistsBuilder_.isEmpty()) {
              checklistsBuilder_.dispose();
              checklistsBuilder_ = null;
              checklists_ = other.checklists_;
              bitField0_ = (bitField0_ & ~0x00000001);
              checklistsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChecklistsFieldBuilder() : null;
            } else {
              checklistsBuilder_.addAllMessages(other.checklists_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage> checklists_ =
        java.util.Collections.emptyList();
      private void ensureChecklistsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          checklists_ = new java.util.ArrayList<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage>(checklists_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder> checklistsBuilder_;

      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage> getChecklistsList() {
        if (checklistsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(checklists_);
        } else {
          return checklistsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public int getChecklistsCount() {
        if (checklistsBuilder_ == null) {
          return checklists_.size();
        } else {
          return checklistsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage getChecklists(int index) {
        if (checklistsBuilder_ == null) {
          return checklists_.get(index);
        } else {
          return checklistsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder setChecklists(
          int index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage value) {
        if (checklistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistsIsMutable();
          checklists_.set(index, value);
          onChanged();
        } else {
          checklistsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder setChecklists(
          int index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder builderForValue) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          checklists_.set(index, builderForValue.build());
          onChanged();
        } else {
          checklistsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder addChecklists(com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage value) {
        if (checklistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistsIsMutable();
          checklists_.add(value);
          onChanged();
        } else {
          checklistsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder addChecklists(
          int index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage value) {
        if (checklistsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChecklistsIsMutable();
          checklists_.add(index, value);
          onChanged();
        } else {
          checklistsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder addChecklists(
          com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder builderForValue) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          checklists_.add(builderForValue.build());
          onChanged();
        } else {
          checklistsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder addChecklists(
          int index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder builderForValue) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          checklists_.add(index, builderForValue.build());
          onChanged();
        } else {
          checklistsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder addAllChecklists(
          java.lang.Iterable<? extends com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage> values) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, checklists_);
          onChanged();
        } else {
          checklistsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder clearChecklists() {
        if (checklistsBuilder_ == null) {
          checklists_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          checklistsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public Builder removeChecklists(int index) {
        if (checklistsBuilder_ == null) {
          ensureChecklistsIsMutable();
          checklists_.remove(index);
          onChanged();
        } else {
          checklistsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder getChecklistsBuilder(
          int index) {
        return getChecklistsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder getChecklistsOrBuilder(
          int index) {
        if (checklistsBuilder_ == null) {
          return checklists_.get(index);  } else {
          return checklistsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public java.util.List<? extends com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder> 
           getChecklistsOrBuilderList() {
        if (checklistsBuilder_ != null) {
          return checklistsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(checklists_);
        }
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder addChecklistsBuilder() {
        return getChecklistsFieldBuilder().addBuilder(
            com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder addChecklistsBuilder(
          int index) {
        return getChecklistsFieldBuilder().addBuilder(
            index, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mining.platform.checklist.ChecklistPackage checklists = 1;</code>
       */
      public java.util.List<com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder> 
           getChecklistsBuilderList() {
        return getChecklistsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder> 
          getChecklistsFieldBuilder() {
        if (checklistsBuilder_ == null) {
          checklistsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackage.Builder, com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistPackageOrBuilder>(
                  checklists_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          checklists_ = null;
        }
        return checklistsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.mining.platform.checklist.ChecklistListPackage)
    }

    // @@protoc_insertion_point(class_scope:com.mining.platform.checklist.ChecklistListPackage)
    private static final com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage();
    }

    public static com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChecklistListPackage>
        PARSER = new com.google.protobuf.AbstractParser<ChecklistListPackage>() {
      public ChecklistListPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ChecklistListPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChecklistListPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ChecklistListPackage> getParserForType() {
      return PARSER;
    }

    public com.mining.platform.checklist.ChecklistPackageOuterClass.ChecklistListPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mining_platform_checklist_ChecklistItemPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mining_platform_checklist_ChecklistItemPackage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mining_platform_checklist_ChecklistPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mining_platform_checklist_ChecklistPackage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mining_platform_checklist_ChecklistListPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mining_platform_checklist_ChecklistListPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ChecklistPackage.proto\022\035com.mining.pla" +
      "tform.checklist\"0\n\024ChecklistItemPackage\022" +
      "\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\"y\n\020ChecklistPa" +
      "ckage\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022K\n\016check" +
      "listItems\030\003 \003(\01323.com.mining.platform.ch" +
      "ecklist.ChecklistItemPackage\"[\n\024Checklis" +
      "tListPackage\022C\n\nchecklists\030\001 \003(\0132/.com.m" +
      "ining.platform.checklist.ChecklistPackag" +
      "eb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mining_platform_checklist_ChecklistItemPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mining_platform_checklist_ChecklistItemPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mining_platform_checklist_ChecklistItemPackage_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_com_mining_platform_checklist_ChecklistPackage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mining_platform_checklist_ChecklistPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mining_platform_checklist_ChecklistPackage_descriptor,
        new java.lang.String[] { "Id", "Name", "ChecklistItems", });
    internal_static_com_mining_platform_checklist_ChecklistListPackage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mining_platform_checklist_ChecklistListPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mining_platform_checklist_ChecklistListPackage_descriptor,
        new java.lang.String[] { "Checklists", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
