// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EquipmentPackage.proto

package com.mining.platform.equipment;

public final class EquipmentPackageOuterClass {
  private EquipmentPackageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EquipmentPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mining.platform.equipment.EquipmentPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes id = 1;</code>
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string shortName = 3;</code>
     */
    java.lang.String getShortName();
    /**
     * <code>optional string shortName = 3;</code>
     */
    com.google.protobuf.ByteString
        getShortNameBytes();

    /**
     * <code>optional string deviceId = 4;</code>
     */
    java.lang.String getDeviceId();
    /**
     * <code>optional string deviceId = 4;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();
  }
  /**
   * Protobuf type {@code com.mining.platform.equipment.EquipmentPackage}
   */
  public  static final class EquipmentPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mining.platform.equipment.EquipmentPackage)
      EquipmentPackageOrBuilder {
    // Use EquipmentPackage.newBuilder() to construct.
    private EquipmentPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EquipmentPackage() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
      shortName_ = "";
      deviceId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EquipmentPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              id_ = input.readBytes();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              shortName_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.class, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>optional bytes id = 1;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHORTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object shortName_;
    /**
     * <code>optional string shortName = 3;</code>
     */
    public java.lang.String getShortName() {
      java.lang.Object ref = shortName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shortName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string shortName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getShortNameBytes() {
      java.lang.Object ref = shortName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEID_FIELD_NUMBER = 4;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>optional string deviceId = 4;</code>
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string deviceId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeBytes(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getShortNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, shortName_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, deviceId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getShortNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, shortName_);
      }
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, deviceId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage)) {
        return super.equals(obj);
      }
      com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage other = (com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getShortName()
          .equals(other.getShortName());
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SHORTNAME_FIELD_NUMBER;
      hash = (53 * hash) + getShortName().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mining.platform.equipment.EquipmentPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mining.platform.equipment.EquipmentPackage)
        com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.class, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder.class);
      }

      // Construct using com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.ByteString.EMPTY;

        name_ = "";

        shortName_ = "";

        deviceId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentPackage_descriptor;
      }

      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage getDefaultInstanceForType() {
        return com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.getDefaultInstance();
      }

      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage build() {
        com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage buildPartial() {
        com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage result = new com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage(this);
        result.id_ = id_;
        result.name_ = name_;
        result.shortName_ = shortName_;
        result.deviceId_ = deviceId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage) {
          return mergeFrom((com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage other) {
        if (other == com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.getDefaultInstance()) return this;
        if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getShortName().isEmpty()) {
          shortName_ = other.shortName_;
          onChanged();
        }
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes id = 1;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object shortName_ = "";
      /**
       * <code>optional string shortName = 3;</code>
       */
      public java.lang.String getShortName() {
        java.lang.Object ref = shortName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shortName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string shortName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getShortNameBytes() {
        java.lang.Object ref = shortName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shortName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string shortName = 3;</code>
       */
      public Builder setShortName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shortName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string shortName = 3;</code>
       */
      public Builder clearShortName() {
        
        shortName_ = getDefaultInstance().getShortName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string shortName = 3;</code>
       */
      public Builder setShortNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shortName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceId_ = "";
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deviceId = 4;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.mining.platform.equipment.EquipmentPackage)
    }

    // @@protoc_insertion_point(class_scope:com.mining.platform.equipment.EquipmentPackage)
    private static final com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage();
    }

    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EquipmentPackage>
        PARSER = new com.google.protobuf.AbstractParser<EquipmentPackage>() {
      public EquipmentPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EquipmentPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EquipmentPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EquipmentPackage> getParserForType() {
      return PARSER;
    }

    public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EquipmentListPackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mining.platform.equipment.EquipmentListPackage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    java.util.List<com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage> 
        getEquipmentsList();
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage getEquipments(int index);
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    int getEquipmentsCount();
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    java.util.List<? extends com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder> 
        getEquipmentsOrBuilderList();
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder getEquipmentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.mining.platform.equipment.EquipmentListPackage}
   */
  public  static final class EquipmentListPackage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mining.platform.equipment.EquipmentListPackage)
      EquipmentListPackageOrBuilder {
    // Use EquipmentListPackage.newBuilder() to construct.
    private EquipmentListPackage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EquipmentListPackage() {
      equipments_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private EquipmentListPackage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                equipments_ = new java.util.ArrayList<com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage>();
                mutable_bitField0_ |= 0x00000001;
              }
              equipments_.add(
                  input.readMessage(com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          equipments_ = java.util.Collections.unmodifiableList(equipments_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentListPackage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentListPackage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage.class, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage.Builder.class);
    }

    public static final int EQUIPMENTS_FIELD_NUMBER = 1;
    private java.util.List<com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage> equipments_;
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    public java.util.List<com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage> getEquipmentsList() {
      return equipments_;
    }
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    public java.util.List<? extends com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder> 
        getEquipmentsOrBuilderList() {
      return equipments_;
    }
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    public int getEquipmentsCount() {
      return equipments_.size();
    }
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage getEquipments(int index) {
      return equipments_.get(index);
    }
    /**
     * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
     */
    public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder getEquipmentsOrBuilder(
        int index) {
      return equipments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < equipments_.size(); i++) {
        output.writeMessage(1, equipments_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < equipments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, equipments_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage)) {
        return super.equals(obj);
      }
      com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage other = (com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage) obj;

      boolean result = true;
      result = result && getEquipmentsList()
          .equals(other.getEquipmentsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getEquipmentsCount() > 0) {
        hash = (37 * hash) + EQUIPMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getEquipmentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mining.platform.equipment.EquipmentListPackage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mining.platform.equipment.EquipmentListPackage)
        com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentListPackage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentListPackage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage.class, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage.Builder.class);
      }

      // Construct using com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEquipmentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (equipmentsBuilder_ == null) {
          equipments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          equipmentsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mining.platform.equipment.EquipmentPackageOuterClass.internal_static_com_mining_platform_equipment_EquipmentListPackage_descriptor;
      }

      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage getDefaultInstanceForType() {
        return com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage.getDefaultInstance();
      }

      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage build() {
        com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage buildPartial() {
        com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage result = new com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage(this);
        int from_bitField0_ = bitField0_;
        if (equipmentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            equipments_ = java.util.Collections.unmodifiableList(equipments_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.equipments_ = equipments_;
        } else {
          result.equipments_ = equipmentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage) {
          return mergeFrom((com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage other) {
        if (other == com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage.getDefaultInstance()) return this;
        if (equipmentsBuilder_ == null) {
          if (!other.equipments_.isEmpty()) {
            if (equipments_.isEmpty()) {
              equipments_ = other.equipments_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEquipmentsIsMutable();
              equipments_.addAll(other.equipments_);
            }
            onChanged();
          }
        } else {
          if (!other.equipments_.isEmpty()) {
            if (equipmentsBuilder_.isEmpty()) {
              equipmentsBuilder_.dispose();
              equipmentsBuilder_ = null;
              equipments_ = other.equipments_;
              bitField0_ = (bitField0_ & ~0x00000001);
              equipmentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEquipmentsFieldBuilder() : null;
            } else {
              equipmentsBuilder_.addAllMessages(other.equipments_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage> equipments_ =
        java.util.Collections.emptyList();
      private void ensureEquipmentsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          equipments_ = new java.util.ArrayList<com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage>(equipments_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder> equipmentsBuilder_;

      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public java.util.List<com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage> getEquipmentsList() {
        if (equipmentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(equipments_);
        } else {
          return equipmentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public int getEquipmentsCount() {
        if (equipmentsBuilder_ == null) {
          return equipments_.size();
        } else {
          return equipmentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage getEquipments(int index) {
        if (equipmentsBuilder_ == null) {
          return equipments_.get(index);
        } else {
          return equipmentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder setEquipments(
          int index, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage value) {
        if (equipmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipmentsIsMutable();
          equipments_.set(index, value);
          onChanged();
        } else {
          equipmentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder setEquipments(
          int index, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder builderForValue) {
        if (equipmentsBuilder_ == null) {
          ensureEquipmentsIsMutable();
          equipments_.set(index, builderForValue.build());
          onChanged();
        } else {
          equipmentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder addEquipments(com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage value) {
        if (equipmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipmentsIsMutable();
          equipments_.add(value);
          onChanged();
        } else {
          equipmentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder addEquipments(
          int index, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage value) {
        if (equipmentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipmentsIsMutable();
          equipments_.add(index, value);
          onChanged();
        } else {
          equipmentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder addEquipments(
          com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder builderForValue) {
        if (equipmentsBuilder_ == null) {
          ensureEquipmentsIsMutable();
          equipments_.add(builderForValue.build());
          onChanged();
        } else {
          equipmentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder addEquipments(
          int index, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder builderForValue) {
        if (equipmentsBuilder_ == null) {
          ensureEquipmentsIsMutable();
          equipments_.add(index, builderForValue.build());
          onChanged();
        } else {
          equipmentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder addAllEquipments(
          java.lang.Iterable<? extends com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage> values) {
        if (equipmentsBuilder_ == null) {
          ensureEquipmentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, equipments_);
          onChanged();
        } else {
          equipmentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder clearEquipments() {
        if (equipmentsBuilder_ == null) {
          equipments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          equipmentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public Builder removeEquipments(int index) {
        if (equipmentsBuilder_ == null) {
          ensureEquipmentsIsMutable();
          equipments_.remove(index);
          onChanged();
        } else {
          equipmentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder getEquipmentsBuilder(
          int index) {
        return getEquipmentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder getEquipmentsOrBuilder(
          int index) {
        if (equipmentsBuilder_ == null) {
          return equipments_.get(index);  } else {
          return equipmentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public java.util.List<? extends com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder> 
           getEquipmentsOrBuilderList() {
        if (equipmentsBuilder_ != null) {
          return equipmentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(equipments_);
        }
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder addEquipmentsBuilder() {
        return getEquipmentsFieldBuilder().addBuilder(
            com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder addEquipmentsBuilder(
          int index) {
        return getEquipmentsFieldBuilder().addBuilder(
            index, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mining.platform.equipment.EquipmentPackage equipments = 1;</code>
       */
      public java.util.List<com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder> 
           getEquipmentsBuilderList() {
        return getEquipmentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder> 
          getEquipmentsFieldBuilder() {
        if (equipmentsBuilder_ == null) {
          equipmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackage.Builder, com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentPackageOrBuilder>(
                  equipments_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          equipments_ = null;
        }
        return equipmentsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.mining.platform.equipment.EquipmentListPackage)
    }

    // @@protoc_insertion_point(class_scope:com.mining.platform.equipment.EquipmentListPackage)
    private static final com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage();
    }

    public static com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EquipmentListPackage>
        PARSER = new com.google.protobuf.AbstractParser<EquipmentListPackage>() {
      public EquipmentListPackage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EquipmentListPackage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EquipmentListPackage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EquipmentListPackage> getParserForType() {
      return PARSER;
    }

    public com.mining.platform.equipment.EquipmentPackageOuterClass.EquipmentListPackage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mining_platform_equipment_EquipmentPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mining_platform_equipment_EquipmentPackage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mining_platform_equipment_EquipmentListPackage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mining_platform_equipment_EquipmentListPackage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026EquipmentPackage.proto\022\035com.mining.pla" +
      "tform.equipment\"Q\n\020EquipmentPackage\022\n\n\002i" +
      "d\030\001 \001(\014\022\014\n\004name\030\002 \001(\t\022\021\n\tshortName\030\003 \001(\t" +
      "\022\020\n\010deviceId\030\004 \001(\t\"[\n\024EquipmentListPacka" +
      "ge\022C\n\nequipments\030\001 \003(\0132/.com.mining.plat" +
      "form.equipment.EquipmentPackageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mining_platform_equipment_EquipmentPackage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mining_platform_equipment_EquipmentPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mining_platform_equipment_EquipmentPackage_descriptor,
        new java.lang.String[] { "Id", "Name", "ShortName", "DeviceId", });
    internal_static_com_mining_platform_equipment_EquipmentListPackage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mining_platform_equipment_EquipmentListPackage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mining_platform_equipment_EquipmentListPackage_descriptor,
        new java.lang.String[] { "Equipments", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
